version: '3.8'

services:
  auth-service:
    image: registry.digitalocean.com/edimy/edu-auth:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://your-frontend-domain.com}
      - PAYHERE_NOTIFY_URL=${PAYHERE_NOTIFY_URL:-https://your-app-url.ondigitalocean.app/api/payments/callback}
      - PAYHERE_RETURN_URL=${PAYHERE_RETURN_URL:-https://your-frontend-domain.com/success}
      - PAYHERE_CANCEL_URL=${PAYHERE_CANCEL_URL:-https://your-frontend-domain.com/cancel}
      - JWT_SECRET=${JWT_SECRET:-your-secure-jwt-secret-key-here}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
