version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-sepgroup15@gmail.com}
      - PAYHERE_MERCHANT_ID=${PAYHERE_MERCHANT_ID}
      - PAYHERE_MERCHANT_SECRET=${PAYHERE_MERCHANT_SECRET}
      - PAYHERE_NOTIFY_URL=${PAYHERE_NOTIFY_URL}
      - PAYHERE_RETURN_URL=${PAYHERE_RETURN_URL}
      - PAYHERE_CANCEL_URL=${PAYHERE_CANCEL_URL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
