# [build]
# builder = "NIXPACKS"

# [build.nixpacksConfig]
# providers = ["java"]

[deploy]
healthcheckPath = "/api/actuator/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { SPRING_PROFILES_ACTIVE = "production" }

[environments.staging]
variables = { SPRING_PROFILES_ACTIVE = "staging" }
