name: edu-auth-app
services:
- name: auth-service
  source_dir: /
  github:
    repo: your-github-username/your-repo-name
    branch: main
  run_command: java -jar app.jar
  environment_slug: docker
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8083
  routes:
  - path: /
  health_check:
    http_path: /actuator/health
  envs:
  - key: SPRING_PROFILES_ACTIVE
    value: production
  - key: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://your-db-host:5432/your-database
    type: SECRET
  - key: SPRING_DATASOURCE_USERNAME
    value: your-username
    type: SECRET
  - key: SPRING_DATASOURCE_PASSWORD
    value: your-password
    type: SECRET

